### ISSUE TITLE
Use ImagePullPolicy: IfNotPresent

### ISSUE THREAD

**Issue by cgwalters** [openshift/library-go#144]
My cluster died this morning when I rebooted it; I believe because the release payload was GC'd, and we were using `Always` for image pull policy.  I *think* this is the code that ends up in the `/etc/kubernetes/static-pods` bits which are used for the API server...if not please redirect me to the right place.

```
diff --git a/pkg/operator/render/options/manifest.go b/pkg/operator/render/options/manifest.go
index 279ea38..e893edf 100644
--- a/pkg/operator/render/options/manifest.go
+++ b/pkg/operator/render/options/manifest.go
@@ -23,7 +23,7 @@ func NewManifestOptions(componentName, image string) *ManifestOptions {
 	return &ManifestOptions{
 		Namespace:             fmt.Sprintf("openshift-%s", componentName),
 		Image:                 image,
-		ImagePullPolicy:       "Always",
+		ImagePullPolicy:       "IfNotPresent",
 		ConfigHostPath:        "/etc/kubernetes/bootstrap-configs",
 		ConfigFileName:        fmt.Sprintf("%s-config.yaml", componentName),
 		CloudProviderHostPath: "/etc/kubernetes/cloud",
```

**Comment by mfojtik** [comment]
The `ImagePullPolicy` was removed from operator config in v1 (I believe //cc @deads2k). There is no way now to set the image pull policy for the installer pod and it will always be always ;-)

**Comment by cgwalters** [comment]
> There is no way now to set the image pull policy for the installer pod and it will always be always ;-)

I am working on upgrade related things, so it's going to be quite annoying if my clusters die just because 1-2 days passed and the release payload was GC'd.

I suppose I can switch my development model to install clusters from released payloads but...do you agree that `Always` is not the correct pull policy here?

**Comment by mfojtik** [comment]
@cgwalters i think Always is the right policy as we always want to pull the latest, up-to-date image for the installer pod. IfNotPresent will mean that we can potentially use outdate image and that might cause even more problems.

What you mean with "release payload" ?

**Comment by cgwalters** [comment]
>  i think Always is the right policy as we always want to pull the latest, up-to-date image for the installer pod.

But all images should come from the release payload and be immutable.  See:

> What you mean with "release payload" ?

https://url.corp.redhat.com/a7a9457

**Comment by bparees** [comment]
We are also using pull policy Always in our operators (samples operator, image-registry operator).  We did that because having to remember to set it to Always when you override the image field (because you're doing local development) was frustrating and Always is basically free anyway.

I was not aware that we are pruning the release payload images so aggressively that this would be a problem for someone trying to run a dev cluster for a few days.  I'd like to understand if we really need to be doing that, before we go mandating a change to everyone's operators to switch back to "IfNotPresent" and the associated headaches that come with that policy.

**Comment by cgwalters** [comment]
> We did that because having to remember to set it to Always when you override the image field (because you're doing local development) was frustrating and Always is basically free anyway.

IMO...the correct thing is to ensure you're always referencing images by digest (i.e. `@sha256:...`).  See what I'm hacking on in https://github.com/openshift/machine-config-operator/pull/231

**Comment by bparees** [comment]
> IMO...the correct thing is to ensure you're always referencing images by digest (i.e. @sha256:...). See what I'm hacking on in openshift/machine-config-operator#231

that looks incredibly painful to maintain as we introduce new workload resources, and in some cases the location where the image reference is stored varies as well.

**Comment by cgwalters** [comment]
Though with by-digest references...what is the difference between `Always` and `IfNotPresent`?  We can't find an update to a by-digest image right?

**Comment by runcom** [comment]
Yes, you can't update a digested image no matter the pull policy afaict

**Comment by bparees** [comment]
> Though with by-digest references...what is the difference between Always and IfNotPresent? We can't find an update to a by-digest image right?

the difference is with IfNotPresent if you've got a copy locally, it doesn't matter if it's been deleted from the registry.  The issue here is that we started the pod once, successfully pulled the image by digest, but then when the pod is being restarted, the Always pull policy means we have to check the registry for it again and it's been deleted.  IfNotPresent would avoid that (but i don't like it as a solution)

**Comment by cgwalters** [comment]
Filed https://github.com/openshift/release/issues/2378
